import type {
  DigiKeyProduct,
  CategoryWithProducts,
} from "@/types/digikey";

// Import curated product data from static JSON files.
// These are generated by scripts/curate_frontend_products.py from the
// DigiKey product index reference data.
import productsData from "../../public/products.json";
import categoriesData from "../../public/categories.json";
import trendingData from "../../public/trending.json";

// ---- Internal Types ----

/** Product entry in products.json includes _category and _categoryName metadata */
interface CuratedProduct extends DigiKeyProduct {
  _category: string;
  _categoryName: string;
}

/** Category entry in categories.json */
interface CuratedCategory {
  name: string;
  slug: string;
  description: string;
  categoryId: number;
  parentId: number;
  productCount: number;
}

// ---- Type-cast imported JSON ----

const allProducts = productsData as CuratedProduct[];
const allCategories = categoriesData as CuratedCategory[];
const trendingProducts = trendingData as DigiKeyProduct[];

// ---- Exported Functions ----

/**
 * Get all featured categories with their products.
 * Returns 8 categories (Capacitors, Resistors, ICs, Connectors,
 * Dev Boards, Sensors, LEDs, Switches) each with 3-5 curated products.
 *
 * The returned shape matches CategoryWithProducts from @/types/digikey,
 * which is what the Section component expects.
 */
export function getCategories(): CategoryWithProducts[] {
  return allCategories.map((cat) => {
    const products = allProducts
      .filter((p) => p._category === cat.slug)
      .map(stripMetadata);
    return {
      name: cat.name,
      slug: cat.slug,
      description: cat.description,
      products,
    };
  });
}

/**
 * Get trending / popular products across categories.
 * Returns a curated selection of interesting products such as
 * development boards, popular ICs, common capacitors, sensors, and LEDs.
 *
 * @param limit - Maximum number of products to return (default: 6)
 */
export function getTrendingProducts(limit: number = 6): DigiKeyProduct[] {
  return trendingProducts.slice(0, limit);
}

/**
 * Get all products belonging to a specific category.
 *
 * @param categorySlug - URL-friendly category identifier (e.g., "capacitors", "integrated-circuits-ics")
 * @returns Array of DigiKeyProduct for the given category, or empty array if not found
 */
export function getProductsByCategory(
  categorySlug: string
): DigiKeyProduct[] {
  return allProducts
    .filter((p) => p._category === categorySlug)
    .map(stripMetadata);
}

// ---- Backward Compatibility ----

/**
 * Re-export CategoryWithProducts as Category for backward compatibility
 * with components that import { Category } from "@/store/products".
 * This will be removed once all components migrate to DigiKey types (Task 5).
 */
export type Category = CategoryWithProducts;

// ---- Internal Helpers ----

/**
 * Remove internal metadata fields (_category, _categoryName) from a product
 * so the returned object matches the DigiKeyProduct interface cleanly.
 */
function stripMetadata(product: CuratedProduct): DigiKeyProduct {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { _category, _categoryName, ...rest } = product;
  return rest;
}
